apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-reader
  namespace: reactive-flux-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: reactive-flux-app
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader
  namespace: reactive-flux-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: reactive-flux-app